export const products = [
    { id: 1, name: "Analog Strap Watch", price: "Rs. 4,500.00", image: "/products/watch-1.png", description: "A classic analog strap watch featuring a minimalist design and durable materials." },
    { id: 2, name: "Black Dial Strap", price: "Rs. 2,500.00", image: "/products/watch-2.png", description: "Elegant black dial watch with a comfortable strap, perfect for everyday wear." },
    { id: 3, name: "Black Dial Classic", price: "Rs. 3,126.00", image: "/products/watch-3.png", description: "Timeless classic design with a bold black dial and premium finish." },
    { id: 4, name: "Black Dial Watch", price: "Rs. 5,450.00", image: "/products/watch-4.png", description: "Sophisticated black dial watch suitable for formal and casual occasions." },
    { id: 5, name: "Brown Strip Watch", price: "Rs. 3,000.00", image: "/products/watch-5.png", description: "Stylish brown strap watch that adds a touch of vintage charm to your look." },
    { id: 6, name: "Classic Brown Strip", price: "Rs. 1,900.00", image: "/products/watch-1.png", description: "Affordable classic brown strap watch, reliable and stylish." },
    { id: 7, name: "Golden Dial Analog", price: "Rs. 3,600.00", image: "/products/watch-2.png", description: "Luxury golden dial analog watch for those who appreciate fine details." },
    { id: 8, name: "Golden Dial Watch", price: "Rs. 1,350.00", image: "/products/watch-3.png", description: "Budget-friendly golden dial watch that doesn't compromise on style." },
    { id: 9, name: "Golden Women Watch", price: "Rs. 2,000.00", image: "/products/watch-4.png", description: "Elegant golden watch designed specifically for women." },
    { id: 10, name: "Silver Metal Watch", price: "Rs. 5,000.00", image: "/products/watch-6.png", description: "Premium silver metal watch with a modern aesthetic." },
    { id: 11, name: "Blue Dial Elegance", price: "Rs. 4,200.00", image: "/products/watch-7.png", description: "Stunning blue dial watch that stands out from the crowd." },
    { id: 12, name: "Rose Gold Classic", price: "Rs. 3,900.00", image: "/products/watch-8.png", description: "Beautiful rose gold watch with a classic design." },
    { id: 13, name: "Modern Silver Time", price: "Rs. 4,800.00", image: "/products/watch-9.png", description: "Sleek and modern silver watch for the contemporary individual." },
    { id: 14, name: "Luxury Gold Reserve", price: "Rs. 5,500.00", image: "/products/watch-10.jpg", description: "Exclusive luxury gold reserve watch for special occasions." },
    { id: 15, name: "Minimalist White", price: "Rs. 3,200.00", image: "/products/watch-11.jpg", description: "Clean and minimalist white dial watch." },
    { id: 16, name: "Rose Gold Elegance", price: "Rs. 6,100.00", image: "/products/watch-12.jpg", description: "High-end rose gold elegance for a premium look." },
    { id: 17, name: "Midnight Black", price: "Rs. 4,500.00", image: "/products/watch-13.jpg", description: "Deep midnight black watch for a stealthy and stylish appearance." },
    { id: 18, name: "Classic Two-Tone", price: "Rs. 5,900.00", image: "/products/watch-14.jpg", description: "Classic two-tone watch combining silver and gold tones." },
];
